const $=s=>document.querySelector(s);let scene=null,original=null,schemaScene=null,selected=null,lastSelected=null,selectedIds=new Set(),history=[],future=[],canvasScale=1,assetManifest=null;
const clone=v=>JSON.parse(JSON.stringify(v));
async function api(path,body){const opt=body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{};const r=await fetch(path,opt);const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||r.statusText);return j}
function validateProject(value){if(!value||!['300hero-layout/1','300arena-layout/1'].includes(value.format)||!Array.isArray(value.nodes))throw new Error('不是有效的 300Hero 界面布局项目');return value}
function applyProject(value,label='布局项目'){if(scene)pushHistory();const loaded=validateProject(value),mode=loaded.mode==='arena'?'arena':'hall';if($('#mode').value!==mode){$('#mode').value=mode;schemaScene=null}const known=new Set(loaded.nodes.map(n=>n.id));if(schemaScene&&schemaScene.mode===loaded.mode){for(const node of schemaScene.nodes)if(!known.has(node.id))loaded.nodes.push(clone(node));loaded.options={...(schemaScene.options||{}),...(loaded.options||{})};loaded.sources=schemaScene.sources;loaded.packSummary=schemaScene.packSummary;loaded.warnings=schemaScene.warnings;loaded.gameDir=schemaScene.gameDir}scene=loaded;original=clone(scene);selected=scene.nodes[0]?.id||null;selectedIds=new Set(selected?[selected]:[]);future=[];$('.resolution-row').hidden=mode!=='arena';$('#hallOptions').hidden=mode==='arena';$('#state').closest('.state-row').hidden=mode==='arena';render();renderInfo();status(`已加载${label}：${scene.nodes.length} 个对象`)}
function status(t,bad=false){$('#status').textContent=t;$('#status').style.color=bad?'#ff8b8b':'#9bd1ff'}
function canvasSize(){return scene?.preview&&scene.mode==='arena'?scene.preview:scene?.canvas||{width:1280,height:800}}
function anchorDelta(n){if(scene?.mode!=='arena')return{x:0,y:0};const c=canvasSize(),a=n.anchor||'top-left';return{x:/right/.test(a)?c.width-1920:/center/.test(a)?(c.width-1920)/2:0,y:/bottom/.test(a)?c.height-1080:/middle/.test(a)?(c.height-1080)/2:0}}
function displayPos(n){const d=anchorDelta(n);return{x:n.x+d.x,y:n.y+d.y}}
function fit(){const v=$('#viewport'),pad=50,c=canvasSize();canvasScale=Math.min((v.clientWidth-pad)/c.width,(v.clientHeight-pad)/c.height,1);$('#canvas').style.transform=`scale(${canvasScale})`;}
function nodeById(id){return scene.nodes.find(n=>n.id===id)}
function selectedNodes(){return scene.nodes.filter(n=>selectedIds.has(n.id))}
function pushHistory(){history.push(clone(scene));if(history.length>80)history.shift();future=[];updateUndo()}
function updateUndo(){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length}
function stateVisible(n){return scene.mode==='arena'||n.state==='all'||n.state===$('#state').value}
function render(){if(!scene)return;renderTree();document.querySelectorAll('[data-option]').forEach(e=>e.checked=!!(scene.options||{})[e.dataset.option]);const c=$('#canvas'),cs=canvasSize();c.style.width=cs.width+'px';c.style.height=cs.height+'px';document.querySelector('.ruler').textContent=`预览画布 ${cs.width} × ${cs.height} · 单击单选，Ctrl 多选，Shift 连选`;c.innerHTML='';scene.nodes.forEach((n,i)=>{const p=displayPos(n),e=document.createElement('div'),picked=selectedIds.has(n.id);e.className='node'+(n.id===selected?' selected':'')+(picked&&n.id!==selected?' multi-selected':'')+(n.locked?' locked':'')+($('#hotzones').checked?' boundary':'')+(!stateVisible(n)?' state-hidden':'');e.dataset.id=n.id;e.style.cssText=`left:${p.x}px;top:${p.y}px;width:${n.width*n.scale}px;height:${n.height*n.scale}px;opacity:${n.visible?n.opacity:0.12};--color:${n.color};z-index:${i+1};`;if(n.assetHint){e.style.backgroundImage=`url('/api/resource?hint=${encodeURIComponent(n.assetHint)}')`;e.classList.add('has-asset')}e.innerHTML=`<span>${n.label}${n.visible?'':'（隐藏）'}</span><i class="resize"></i>`;e.addEventListener('pointerdown',pointerDown);c.appendChild(e)});c.classList.toggle('grid',$('#grid').checked);showProps();fit()}
function renderTree(){const root=$('#tree'),scrollTop=root.scrollTop;root.innerHTML='';const groups={};scene.nodes.forEach(n=>(groups[n.group]??=[]).push(n));Object.entries(groups).forEach(([g,items])=>{const sec=document.createElement('section');sec.className='tree-group';sec.innerHTML=`<h3><span>${g}</span><button type="button">全选本组</button></h3>`;sec.querySelector('button').onclick=()=>setSelection(items.map(n=>n.id),items[0]?.id);items.forEach(n=>{const e=document.createElement('div');e.className='tree-item'+(selectedIds.has(n.id)?' selected':'')+(n.visible?'':' off');e.dataset.id=n.id;e.innerHTML=`<input type="checkbox" ${selectedIds.has(n.id)?'checked':''} aria-label="选择 ${n.label}"><span class="eye" title="显示或隐藏">${n.visible?'◉':'○'}</span><span>${n.label}</span><small>${n.locked?'🔒':''}</small>`;e.onclick=ev=>{if(ev.target.matches('input,.eye'))return;select(n.id,{toggle:ev.ctrlKey||ev.metaKey,range:ev.shiftKey})};e.querySelector('input').onclick=ev=>{ev.stopPropagation();select(n.id,{toggle:true})};e.querySelector('.eye').onclick=ev=>{ev.stopPropagation();pushHistory();n.visible=!n.visible;render()};sec.appendChild(e)});root.appendChild(sec)});root.scrollTop=scrollTop}
function setSelection(ids,primary=null){selectedIds=new Set(ids.filter(Boolean));selected=primary&&selectedIds.has(primary)?primary:(selectedIds.values().next().value||null);lastSelected=selected;render()}
function select(id,{toggle=false,range=false}={}){if(!id)return;if(range&&lastSelected){const a=scene.nodes.findIndex(n=>n.id===lastSelected),b=scene.nodes.findIndex(n=>n.id===id);if(a>=0&&b>=0){const ids=scene.nodes.slice(Math.min(a,b),Math.max(a,b)+1).map(n=>n.id);selectedIds=new Set([...selectedIds,...ids]);selected=id}}else if(toggle){if(selectedIds.has(id))selectedIds.delete(id);else selectedIds.add(id);selected=selectedIds.has(id)?id:(selectedIds.values().next().value||null);lastSelected=id}else{selectedIds=new Set([id]);selected=id;lastSelected=id}render()}
function showProps(){const n=nodeById(selected),count=selectedIds.size;$('#selectionCount').textContent=count+' 项';$('#empty').hidden=!!n;$('#props').hidden=!n;if(!n)return;$('#propTitle').textContent=count>1?`已选择 ${count} 个板块（统一修改）`:n.label;for(const k of ['x','y','width','height','scale','opacity'])$('#'+k).value=n[k];$('#visible').checked=n.visible;$('#locked').checked=n.locked;$('#assetHint').value=n.assetHint||'';$('#anchorRow').hidden=scene.mode!=='arena';$('#anchor').value=n.anchor||'top-left';$('#opacityValue').textContent=Math.round(n.opacity*100)+'%';$('#group').value=count>1?'多个分组':n.group;$('#note').value=count>1?'修改右侧属性会应用到全部已选板块':n.note||'';const src=n.source;$('#source').innerHTML=count>1?`${count} 个板块已选中`:`${src.internalPath}<br>包：${src.pack} #${src.index??'-'}<br>行：${src.line??'-'} · ${src.needle}`}
function bindProp(id,key,kind='number'){const e=$('#'+id);e.addEventListener('change',()=>{const nodes=selectedNodes();if(!nodes.length)return;pushHistory();const value=kind==='bool'?e.checked:Number(e.value);nodes.forEach(n=>n[key]=value);render()});if(id==='opacity')e.addEventListener('input',()=>{$('#opacityValue').textContent=Math.round(e.value*100)+'%'})}
['x','y','width','height','scale','opacity'].forEach(k=>bindProp(k,k));bindProp('visible','visible','bool');bindProp('locked','locked','bool');
function pointerDown(ev){const el=ev.currentTarget,n=nodeById(el.dataset.id),toggle=ev.ctrlKey||ev.metaKey,range=ev.shiftKey;if(toggle||range){select(n.id,{toggle,range});return}selectedIds=new Set([n.id]);selected=n.id;lastSelected=n.id;document.querySelectorAll('.node').forEach(x=>{x.classList.toggle('selected',x.dataset.id===n.id);x.classList.remove('multi-selected')});renderTree();showProps();if(n.locked)return;ev.preventDefault();const resizing=ev.target.classList.contains('resize'),sx=ev.clientX,sy=ev.clientY,base=clone(n);pushHistory();el.setPointerCapture(ev.pointerId);const move=e=>{const dx=(e.clientX-sx)/canvasScale,dy=(e.clientY-sy)/canvasScale;if(resizing){n.width=Math.max(10,Math.round(base.width+dx/n.scale));n.height=Math.max(10,Math.round(base.height+dy/n.scale))}else{n.x=Math.round(base.x+dx);n.y=Math.round(base.y+dy)}const p=displayPos(n);el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.width=(n.width*n.scale)+'px';el.style.height=(n.height*n.scale)+'px';showProps()};const up=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);render()};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)}
async function load(mode=$('#mode').value){try{status(`正在扫描全部 JMP 并定位${mode==='arena'?'竞技场':'大厅'} Lua…`);scene=await api('/api/scene?mode='+mode);schemaScene=clone(scene);original=clone(scene);$('#gameDir').value=scene.gameDir;selected=scene.nodes[0]?.id;selectedIds=new Set(selected?[selected]:[]);history=[];future=[];$('.resolution-row').hidden=mode!=='arena';$('#hallOptions').hidden=mode==='arena';$('#state').closest('.state-row').hidden=mode==='arena';if(mode==='arena'){const p=scene.preview||{width:1280,height:800};$('#resolution').value=`${p.width}x${p.height}`}render();renderInfo();await renderAssetsInfo();await refreshProjects();status(`分析完成：${Object.keys(scene.sources).length} 个 Lua，${scene.nodes.length} 个可编辑板块`)}catch(e){status('分析失败：'+e.message,true)}}
function renderInfo(){const w=$('#warnings'),missing=scene.warnings||[],bad=(scene.packSummary||[]).filter(p=>!p.ok);w.innerHTML=`<div class="ok">✓ 已定位 ${Object.keys(scene.sources).length} 个相关 Lua</div><div>JMP：${(scene.packSummary||[]).length} 个</div>`+missing.map(x=>`<div class="warn">⚠ ${x}</div>`).join('')+bad.map(x=>`<div class="warn">⚠ ${x.name}: ${x.error}</div>`).join('')}
async function renderAssetsInfo(){assetManifest=await api('/api/assets');const a=assetManifest;$('#assetsInfo').innerHTML=`<div class="ok">✓ ${a.resourceCount||0} 个原始资源</div><div>${a.previewCount||0} 个网页预览</div><div>${((a.totalBytes||0)/1048576).toFixed(2)} MiB</div><div>属性中的“显示资源”可搜索并替换预览素材</div>`;const list=$('#assetOptions');list.innerHTML='';(a.resources||[]).filter(x=>x.preview).forEach(x=>{const o=document.createElement('option');o.value=x.internalPath;list.appendChild(o)})}
async function refreshProjects(){const data=await api('/api/projects'),sel=$('#savedProjects'),old=sel.value;sel.innerHTML='<option value="">上次保存的布局…</option>';data.projects.forEach(p=>{const o=document.createElement('option');o.value=p.file;o.textContent=`${p.name} (${new Date(p.modified*1000).toLocaleString()})`;sel.appendChild(o)});if([...sel.options].some(o=>o.value===old))sel.value=old}
$('#selectGameDir').onclick=async()=>{try{status('请选择包含 Data*.jmp 的游戏目录…');const r=await api('/api/select-game-dir');$('#gameDir').value=r.gameDir;await load($('#mode').value)}catch(e){status('选择目录失败：'+e.message,true)}};
$('#analyze').onclick=async()=>{try{status('重新分析中…');scene=await api('/api/analyze',{gameDir:$('#gameDir').value,mode:$('#mode').value});schemaScene=clone(scene);original=clone(scene);selected=scene.nodes[0]?.id;selectedIds=new Set(selected?[selected]:[]);history=[];future=[];render();renderInfo();status('重新分析完成')}catch(e){status('分析失败：'+e.message,true)}};
$('#extractAssets').onclick=async()=>{try{status('正在从全部 JMP 抽取大厅资源，请稍候…');const a=await api('/api/extract-assets',{});await renderAssetsInfo();render();status(`抽取完成：${a.resourceCount} 个资源，${a.previewCount} 个网页预览`)}catch(e){status('资源抽取失败：'+e.message,true)}};
$('#assetHint').onchange=()=>{const n=nodeById(selected);if(!n)return;pushHistory();n.assetHint=$('#assetHint').value;render()};
$('#anchor').onchange=()=>{const n=nodeById(selected);if(!n)return;pushHistory();const p=displayPos(n);n.anchor=$('#anchor').value;const d=anchorDelta(n);n.x=Math.round(p.x-d.x);n.y=Math.round(p.y-d.y);render()};
$('#save').onclick=async()=>{try{const name=prompt('项目名称',scene.mode==='arena'?'竞技场布局项目':'大厅布局项目');if(!name)return;const r=await api('/api/save',{name,scene});await refreshProjects();status('项目已保存：'+r.path+'；尚未写入游戏 JMP')}catch(e){status('保存失败：'+e.message,true)}};
$('#export').onclick=async()=>{try{const r=await api('/api/export',{scene});status('已导出：'+r.path)}catch(e){status('导出失败：'+e.message,true)}};
$('#loadSaved').onclick=async()=>{const file=$('#savedProjects').value;if(!file){status('请先选择一个已保存布局',true);return}try{applyProject(await api('/api/load-project',{file}),'已保存布局')}catch(e){status('加载失败：'+e.message,true)}};
$('#importFile').onclick=()=>$('#projectFile').click();
$('#projectFile').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{applyProject(JSON.parse(await file.text()),file.name)}catch(e){status('导入失败：'+e.message,true)}finally{ev.target.value=''}};
$('#previewPatch').onclick=async()=>{try{status('正在生成 Lua 差异…');const data=await api('/api/preview-patch',{scene});const text=data.files.map(f=>`===== ${f.pack} · ${f.path} =====\n${f.diff}`).join('\n');$('#diffText').textContent=text||'没有变化';$('#diffDialog').showModal();status(`已生成 ${data.files.length} 个 Lua 的差异预览`)}catch(e){status('差异生成失败：'+e.message,true)}};
$('#closeDiff').onclick=()=>$('#diffDialog').close();
$('#generatePatch').onclick=async()=>{try{const r=await api('/api/generate-patch',{scene});status('游戏 Lua 补丁已生成：'+r.path)}catch(e){status('补丁生成失败：'+e.message,true)}};
$('#applyGame').onclick=async()=>{if(!confirm('将把当前布局写入游戏 JMP。程序会先自动备份并在写入后校验。建议先关闭游戏和启动器。是否继续？'))return;try{status('正在备份并写入游戏 JMP，请勿关闭程序…');const r=await api('/api/apply-game',{scene});status(`应用完成：已写入 ${r.count} 个 Lua；上一个版本：${r.previousVersion}`)}catch(e){status('应用失败：'+e.message,true)}};
$('#restoreGame').onclick=async()=>{if(!confirm('将使用本编辑器保存的首次原始备份恢复大厅 Lua。是否继续？'))return;try{status('正在恢复原版大厅 Lua…');const r=await api('/api/restore-game',{});status(`恢复完成：${r.count} 个 Lua`)}catch(e){status('恢复失败：'+e.message,true)}};
$('#selectAll').onclick=()=>setSelection(scene.nodes.map(n=>n.id),scene.nodes[0]?.id);$('#invertSelection').onclick=()=>{const ids=scene.nodes.filter(n=>!selectedIds.has(n.id)).map(n=>n.id);setSelection(ids,ids[0])};$('#clearSelection').onclick=()=>setSelection([]);
$('#undo').onclick=()=>{if(!history.length)return;future.push(clone(scene));scene=history.pop();render();updateUndo()};$('#redo').onclick=()=>{if(!future.length)return;history.push(clone(scene));scene=future.pop();render();updateUndo()};
$('#state').onchange=render;$('#hotzones').onchange=render;$('#grid').onchange=render;$('#canvas').onclick=()=>{selected=null;selectedIds.clear();render()};window.onresize=fit;
$('#mode').onchange=()=>load($('#mode').value);$('#resolution').onchange=()=>{const [width,height]=$('#resolution').value.split('x').map(Number);scene.preview={width,height};render()};
document.querySelectorAll('[data-option]').forEach(e=>e.onchange=()=>{pushHistory();scene.options=scene.options||{};scene.options[e.dataset.option]=e.checked;render()});
document.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>{const nodes=selectedNodes().filter(n=>!n.locked);if(!nodes.length)return;pushHistory();const a=b.dataset.align,c=canvasSize();nodes.forEach(n=>{const d=anchorDelta(n);if(a==='left')n.x=-d.x;if(a==='right')n.x=c.width-n.width*n.scale-d.x;if(a==='center')n.x=(c.width-n.width*n.scale)/2-d.x;if(a==='top')n.y=-d.y;if(a==='bottom')n.y=c.height-n.height*n.scale-d.y;if(a==='middle')n.y=(c.height-n.height*n.scale)/2-d.y;n.x=Math.round(n.x);n.y=Math.round(n.y)});render()});
$('#resetNode').onclick=()=>{const nodes=selectedNodes();if(!nodes.length)return;pushHistory();nodes.forEach(n=>{const o=original.nodes.find(x=>x.id===n.id);if(o)Object.assign(n,clone(o))});render()};
updateUndo();load();
